### ISSUE TITLE
mds-client crashing because of missing library

### ISSUE THREAD

**Issue by apowers313** [apowers313/fido2-server#5]
For some reason `npm install` for `fido2-server` isn't installing the dependencies for `mds-client`. The symptom is that the first time the server is run it will fail with an error like:

> Downloading entry: https://mds.fidoalliance.org/metadata/0013%230071
Downloading entry: https://mds.fidoalliance.org/metadata/0013%230084
Downloading entry: https://mds.fidoalliance.org/metadata/0014%23FFF1
/private/tmp/fido2-server/node_modules/mds-client/mds.js:89
                    var md = new KJUR.crypto.MessageDigest({
>                                 ^
>
>ReferenceError: KJUR is not defined
    at MdsClient.<anonymous> (/private/tmp/fido2-server/node_modules/mds-client/mds.js:89:34)
    at Request.self.callback (/private/tmp/fido2-server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/private/tmp/fido2-server/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/private/tmp/fido2-server/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Looking at `node_modules/mds-client` there is no `node_modules/mds-client/node-modules` directory and `mds-client/package.json` has been modified to look like:

``` json
{
  "_args": [
    [
      {
        "raw": "mds-client@^1.1.1",
        "scope": null,
        "escapedName": "mds-client",
        "name": "mds-client",
        "rawSpec": "^1.1.1",
        "spec": ">=1.1.1 <2.0.0",
        "type": "range"
      },
      "/private/tmp/fido2-server"
    ]
  ],
  "_from": "mds-client@>=1.1.1 <2.0.0",
  "_id": "mds-client@1.1.1",
  "_inCache": true,
  "_location": "/mds-client",
  "_nodeVersion": "4.4.0",
  "_npmOperationalInternal": {
    "host": "packages-16-east.internal.npmjs.com",
    "tmp": "tmp/mds-client-1.1.1.tgz_1463470048294_0.7144539810251445"
  },
  "_npmUser": {
    "name": "apowers313",
    "email": "apowers@ato.ms"
  },
  "_npmVersion": "2.15.0",
  "_phantomChildren": {},
  "_requested": {
    "raw": "mds-client@^1.1.1",
    "scope": null,
    "escapedName": "mds-client",
    "name": "mds-client",
    "rawSpec": "^1.1.1",
    "spec": ">=1.1.1 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/mds-client/-/mds-client-1.1.1.tgz",
  "_shasum": "fb64b9852d14155d2d0d197bf55ba042c51fbb10",
  "_shrinkwrap": null,
  "_spec": "mds-client@^1.1.1",
  "_where": "/private/tmp/fido2-server",
  "author": {
    "name": "Adam Powers"
  },
  "bugs": {
    "url": "https://github.com/apowers313/mds-client/issues"
  },
  "dependencies": {
    "async": "^2.0.0-rc.4",
    "js-base64": "^2.1.9",
    "jsonwebtoken": "^5.5.4",
    "jsrsasign": "^5.0.7",
    "lodash": "^4.12.0",
    "request": "^2.69.0"
  },
  "description": "FIDO Metadata Service (MDS) Client",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "fb64b9852d14155d2d0d197bf55ba042c51fbb10",
    "tarball": "https://registry.npmjs.org/mds-client/-/mds-client-1.1.1.tgz"
  },
  "gitHead": "61398238fdcfec0e2e885e6db685d88cd3651751",
  "homepage": "https://github.com/apowers313/mds-client#readme",
  "keywords": [
    "fido",
    "metadata",
    "webauth",
    "webauthn",
    "mds"
  ],
  "license": "MIT",
  "main": "mds.js",
  "maintainers": [
    {
      "name": "apowers313",
      "email": "apowers@ato.ms"
    }
  ],
  "name": "mds-client",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/apowers313/mds-client.git"
  },
  "scripts": {},
  "version": "1.1.1"
}
```

**Comment by apowers313** [comment]
Turns out `jsrsasign` changed its API, but not its major version somewhere between `5.0.7` and `5.1.0`. After pinning `mds-client`'s dependency to `5.0.7` this seems to be fixed.
